---
title: "RQ1 summary code"
author: "Erica Zaja"
date: '2022-04-14'
output: pdf_document
---

### Mapping and sampling

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warming = FALSE}
## LOADING LIBRARIES -----
library(sp)
library(raster)
library(ggplot2)
library(viridis)
library(rasterVis)
library(sf)
library(tidyverse)
```


```{r}
## LOADING DATA ----

# SHRUB DATA: from Berner et al 2018
# Loading raster of shrub biomass (g/m2) on Alaskan North Slope  
shrub_agb_p50 <- raster("datasets/berner_data/shrub_agb_p50.tif") 
# Using the best-estimates: the 50th percentile of the 1,000 permutations

# PCH CORE RANGE DATA: from Porcupine Caribou Management Board (2016)
# Loading polygon of PCH range 
PCH_core_range <- st_read("datasets/PCH_Core_Range_2016/PCH_Core_Range_2016.shp") # loading data
st_bbox(PCH_core_range) # extent of the PCH range

```

```{r}
## EXPLORING DATA ------

# class: what type of data 
class(shrub_agb_p50) # RasterLayer
class(PCH_core_range) # sf dataframe

# resolution of shrub map 
res(shrub_agb_p50) # resolution of map: [1] 30m x 30m

```

```{r}
## CROPPING -----

# Cropping shrub raster to the PCH range 
r2 <- crop(shrub_agb_p50, extent(PCH_core_range))
r3 <- mask(r2, PCH_core_range)
plot(r3) # plot cropped raster
plot(PCH_core_range, add = TRUE, lwd = 2)

# transforming CRS of cropped map from proj = aea (alaska albers) to proj = lalong 
r3_latlong <- projectRaster(r3, crs="+init=EPSG:4326", xy = TRUE)

```

```{r}
## AGGREGATION ----

# aggregate shrub data to coarser resolution before extraction using aggregate()
# factor chosen dividing climate cell resolution 0.008333333 x 0.008333333 by the resolution of the cropped shrub map (latlong)
r3_latlong_agg <- aggregate(r3_latlong, fact=c(11.47842,30.8642), fun = mean, expand = TRUE) 
```

```{r}
# RANDOM SAMPLE WHOLE MAP ----

# Measuring area of raster
# get sizes of all cells in raster [km2]
cell_size <- area(r3_latlong_agg, na.rm=TRUE, weights=FALSE)
# delete NAs from vector of all raster cells
# NAs lie outside of the rastered region, can thus be omitted
cell_size <- cell_size[!is.na(cell_size)] # 0.2815663
#compute area [km2] of all cells in geo_raster
raster_area <-length(cell_size)*median(cell_size)
# print area of shrub map according to raster object
print(paste("Area of PCH Alaskan range (raster)", round(raster_area, digits = 1),"km2"))


# Buffered random sampling 

# a. Extracting all pixels (9583)
r3_rsample_00 <- as.data.frame(sampleRandom(r3_latlong_agg, 9583, buffer = 1414.2, na.rm=TRUE, ext=NULL, 
                                            cells=TRUE, rowcol=FALSE, xy = TRUE)) 

hist(r3_rsample_00$r3_latlong_agg)

# Checking buffer works
# calculating Haversine distance between points (x and y coordinates)
r3_rsample_01 <- r3_rsample_1  %>% 
  mutate(r3_rsample_1, Distance = distHaversine(cbind(x, y),
                                                cbind(lag(x), lag(y))))

# If distance between points > buffer distance, buffer works
r3_rsample_01 <- r3_rsample_01 %>% 
  mutate(buff = case_when(Distance >= 1414.2 ~ "T", Distance < 1414.2 ~ "F"))

r3_rsample_01 <- r3_rsample_01 %>%  filter(buff %in% c("T")) # only keeping obseervations where buff worked
```

```{r}
## DATA VISUALISATION -----

# setting a personalised theme 
theme_shrub <- function(){ theme(legend.position = "right",
                                 axis.title.x = element_text(face="bold", size=20),
                                 axis.text.x  = element_text(vjust=0.5, size=18, colour = "black"), 
                                 axis.title.y = element_text(face="bold", size=20),
                                 axis.text.y  = element_text(vjust=0.5, size=18, colour = "black"),
                                 panel.grid.major.x=element_blank(), panel.grid.minor.x=element_blank(), 
                                 panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(), 
                                 panel.background = element_blank(), axis.line = element_line(colour = "black"), 
                                 plot.title = element_text(color = "black", size = 18, face = "bold", hjust = 0.5),
                                 plot.margin = unit(c(1,1,1,1), units = , "cm"))}

# 1. FULL Shrub map ----

# Plotting shrub raster (entire) with ggplot
(gplot_shrub_agb_p50 <- gplot(shrub_agb_p50) +
    geom_raster(aes(x = x, y = y, fill = value)) +
    # value is the specific value (of reflectance) each pixel is associated with
    scale_fill_viridis_c(rescaler = function(x, to = c(0, 1), from = NULL) {
      ifelse(x<1000, scales::rescale(x, to = to, from = c(min(x, na.rm = TRUE), 1000)),1)}, na.value="white") +
    coord_quickmap()+
    theme_shrub() + 
    xlab("\nLongitude") +
    ylab("Latitude\n") +
    ggtitle("Shrub biomass cover (g/m2) of Alaskan north slope\n") +
    theme(plot.title = element_text(hjust = 0.5),     # centres plot title
          text = element_text(size=15),		       	    # font size
          axis.text.x = element_text(angle = 0, hjust = 1)))  # rotates x axis text


# 2. FULL PCH range ----
# Plotting PCH core range (entire) using ggplot
(PCH_range_map <- ggplot() + 
    geom_sf(data = PCH_core_range, size = 0.5, color = "black", fill = "white") + 
    theme_shrub()+
    ggtitle("PCH core range 2016")) 
```



## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
