---
title: "RQ2_summary_01"
author: "Erica Zaja"
date: '2022-04-15'
output: pdf_document
---

## RQ2: how does biomass vary with temperature and precipitation?

### Script credit: adapted from Joseph Everest and Mariana Garcia Criado

### Part 1: CLIMATE DATA EXTRACTION ----

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, warning = FALSE, message = FALSE}
# LOADING LIBRARIES -----
library(sp)
library(rgdal)
library(raster)
library(ggplot2)
library(viridis)
library(rasterVis)
library(lme4)
library(ggpubr)
library(corrplot)
library(Hmisc)

```



```{r , echo=FALSE, warning = FALSE, message = FALSE}
# LOADING DATA ------

# Climate data from CHELSA 2022
temp <- raster("../../datasets/climate_data/CHELSA_bio10_10.tif") 
# Temperature climatologies: mean daily mean air temperatures 
# of the warmest quarter (bio10) (°C). Offset -273.15

precip <- raster("../../datasets/climate_data/CHELSA_bio10_18.tif")
# Precipitation climatologies: mean monthly precipitation amount 
# of the warmest quarter (bio18) (kg m-2)

```

```{r, message=FALSE, warning=FALSE}
# EXTRACTION ------

# Loading the coordinates of the cropped shrub map
coords <- read.csv("../../datasets/berner_data/r3_rsample_002.csv") %>% 
  dplyr::select(longitude, latitude) # keeping lat and long

# Creating SpatialPoints (sp) object of unique coordinates
coords_sp <- SpatialPoints(coords)

# creating raster stack
chelsa.stack <- stack(precip, temp)

# Extracting variables values for each pair of coordinates
chelsa.extract <- raster::extract(chelsa.stack, coords_sp, df = TRUE) # extract coords 

# Combining dataframes:
# Converting the SpatialPoints (sp) object into a dataframe 
coord.df <- as.data.frame(coords_sp)

# Reassigning the 'ID' to the coordinates dataframe
coord.df$ID <- row.names(coord.df)
coord.df$ID <- as.numeric(coord.df$ID) # Make numeric

# Merging the two dataframes: extracted CHELSA variables and the coordinates
coord.chelsa.combo <- left_join(chelsa.extract, coord.df, by = c("ID" = "ID"))

# Loading the shrub biomass df
biomass.df <- read.csv("../../datasets/berner_data/r3_rsample_002.csv") %>%
  rename(ID = X) %>%
  dplyr::select(ID, biomass, gridcell)

hist(biomass.df$biomass)

# Merging biomass df with climate df
coord.chelsa.combo.a <- left_join(coord.chelsa.combo, biomass.df, by = c("ID" = "ID"))

# Modifying some of the variables to more useful values
coord.chelsa.combo.b <- coord.chelsa.combo.a %>% 
  mutate(CHELSA_bio10_10 = CHELSA_bio10_10/10) # Divide by 10 to get to degC

# Renaming the variables to shorter column headings
coord.chelsa.combo.c <- coord.chelsa.combo.b %>% 
  rename(CH_TempMeanSummer = CHELSA_bio10_10,
         CH_PrecipMeanSummer = CHELSA_bio10_18) %>% na.omit()

unique(coord.chelsa.combo.c$CH_TempMeanSummer)

# Exporting the dataframe to csv
# write.csv(coord.chelsa.combo.c, "../../datasets/climate_data/coord_chelsa_combo_new.csv")
```

### Part 2: MODELLING ----

```{r, message = FALSE}
# DATA MANIPULATION ----
range(coord.chelsa.combo.c$CH_TempMeanSummer) # 7 11
range(coord.chelsa.combo.c$CH_PrecipMeanSummer) # 61 131

```

```{r}
# MODELLING ----

# Standardising explanatory variables
coord.chelsa.combo.c$CH_TempMeanSummer <- scale(coord.chelsa.combo.c$CH_TempMeanSummer, 
                                                center = TRUE, scale = TRUE)
coord.chelsa.combo.c$CH_PrecipMeanSummer <- scale(coord.chelsa.combo.c$CH_PrecipMeanSummer,
                                                  center = TRUE, scale = TRUE)

# MODEL 3: biomass ~ temp  ----
model_3 <- lm(biomass ~ CH_TempMeanSummer, data = coord.chelsa.combo.c)
summary(model_3)

# Checking model 3 assumptions
plot(model_3)
qqnorm(resid(model_3))
qqline(resid(model_3))  # points fall nicely onto the line - good!

```

```{r, fig.show='hide'}
# Extracting model predictions 
predictions_3 <- as.data.frame(predict(model_3, newdata = coord.chelsa.combo.c, 
                                       interval = "confidence")) 
model_3_preds <- cbind(coord.chelsa.combo.c, predictions_3)

# Plot the predictions 
(predictions_biomass_vs_temp <- (ggplot(model_3_preds, aes(CH_TempMeanSummer, fit)) + 
                                geom_point(data = model_3_preds, 
                                           aes(x= CH_TempMeanSummer, y =biomass), 
                                           colour = "#006146", size = 0.5) +
                                  stat_smooth(method=lm, colour = "black", size = 2)+
                                  geom_line(aes(y=lwr),  color = "#F96E00", 
                                            linetype = "dashed", size = 0.5)+
                                  geom_line(aes(y=upr), color = "#F96E00", 
                                            linetype = "dashed", size = 0.5)+
                                   annotate(geom = "text", x = 0, y = 800, 
                                            label="slope = 38.033*** ", size = 10) +
                                  xlab("Scaled mean summer temperature (°C)") +
                                  ylab(bquote("Shrub biomass "*(g~m^-2)*"")) + 
                                         theme_shrub()+
                                   theme(axis.title.x =element_text(size=25, face = "plain"),
                                         axis.title.y =element_text(size=25),
                                         axis.text.x = element_text(size=25, hjust = 1),
                                         axis.text.y = element_text(size=25, hjust = 1) )) )


# analogous code and procedure for model 4 but with mean summer precipitation
```

```{r, fig.show = "hide", message = FALSE}
# MODEL 5: biomass ~ temp*precip ----

# To display interaction: categorise precipitation into'low', 'medium', 'high': 
# Plot 3 lines in plot with temp on the x and biomass on y and points coloured 
# by precipitation level
range(coord.chelsa.combo.c$CH_PrecipMeanSummer)

# quantiles
quantile(coord.chelsa.combo.c$CH_PrecipMeanSummer)
#0%         25%         50%         75%        100% 
#-2.21492909 -0.70752311 -0.03756489  0.54864855  4.14967397 
mean(coord.chelsa.combo.c$CH_PrecipMeanSummer)
# 86.44856 (not standardised)

# Categorising into precipitation levels using quantiles
coord.chelsa.combo.d <- coord.chelsa.combo.c %>% 
  mutate(precip_level = case_when(CH_PrecipMeanSummer < -0.71467025~ "Low",
                              CH_PrecipMeanSummer >= -0.71467025 & CH_PrecipMeanSummer 
                              < 0.56418805  ~ "Medium",
                              CH_PrecipMeanSummer >= 0.56418805  ~ "High"))

unique(coord.chelsa.combo.d$precip_level) # 3 precip levels

# Making precipitation level a factor
coord.chelsa.combo.d$precip_level <- as.factor(as.character
                                               (coord.chelsa.combo.d$precip_level)) 

# Model 5a: biomass Vs temp*precipitation level
model_5a <- lm(biomass ~ CH_TempMeanSummer*precip_level, data = coord.chelsa.combo.d)
summary(model_5a)

# extracting and plotting model predictions

# saving model outputs
#  tab_model(model_5a, file = "output/tables/model_5a.html")
# webshot("output/tables/model_5a.html", "output/tables/model_5a.png")
 
```

```{r, fig.show = FALSE, warning = FALSE}
# ASSUMPTION CHECK -----

coord.chelsa.combo.e <- coord.chelsa.combo.c %>%
  dplyr::select(CH_PrecipMeanSummer,CH_TempMeanSummer, longitude, latitude, biomass )

# making correlation heat map using Spearman correlation
# only keeping significant relationships 
corrplot(cor(coord.chelsa.combo.e, method="s"), sig.level = 0.05, insig = "blank") 
rcorr(as.matrix(coord.chelsa.combo.e))

```

