---
title: "RQ4_summary"
author: "Erica Zaja"
date: '2022-04-15'
output: pdf_document
---

# RQ4: How has shrub phenology (greening) changed over time in or near the PCH range?
### Credit for help: Joseph Everest 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message = FALSE}
# LOADING LIBRARIES -----
library(tidyverse)
library(lme4)
library(ggeffects)
```


```{r, message = FALSE}
# LOADING DATA  -----
phenology_data <- read_csv("../../datasets/phenology_data/CCIN13215_20210302_tundra_phenology_database.csv")
```


```{r, message = FALSE}

# DATA WRANGLING  -----
range(phenology_data$year)# 1992-2019
unique(phenology_data$year) # Unique site names

# Retaining only locations on Alaskan north slope or close to PCH range
phenology_new <- phenology_data %>%
  filter(study_area %in% c("Atqasuk", "Toolik Lake","Qikiqtaruk", "Utqiagvik"))
# Keeping Toolik lake and Qikiqtaruk (close enough to PCH summer range). 
# and  Atqasuk and Utqiaġvik that are on the North slope of Alaska

# keeping shrubs only 
phenology_new <- phenology_new %>%
  filter(functional_group %in% c("evergreen shrub", "deciduous shrub"))

# Standardising names
phenology_new$phenophase[phenology_new$phenophase == "Green"] <- "green"

# filter for greening only
phenology_green <- phenology_new %>%
  filter(phenophase == "green")

hist(phenology_green$DOY)

# Create a new version of phenology_green with unique plot identifiers
phenology_green_id <- phenology_green %>% 
  mutate(SiteSubsitePlot = paste(study_area, ":", subsite, ":", plot)) %>% 
  mutate(SiteSubsitePlotYear = paste(study_area, ":", subsite, ":", plot, ":", year))

# Calculating the mean DOY
phenology_mean_doy <- phenology_green_id %>% 
  group_by(SiteSubsitePlotYear) %>% 
  mutate(mean.doy = mean(DOY)) %>% 
  ungroup()

# Shrinking the dataframe to retain one row per plot etc.
phenology_green_trim <- phenology_mean_doy %>% 
  dplyr::select(study_area, subsite, plot, year, SiteSubsitePlotYear, SiteSubsitePlot,
                lat, long, elevation, ecosystem, exstart, soil_moisture, treatment, mean.doy) %>% 
  distinct(SiteSubsitePlotYear, mean.doy, .keep_all = TRUE) %>% # 2980 rows, perfect!
  mutate(year_index = case_when (year == 1994 ~ '1', year == 1995 ~ '2', 
                                 year == 1996 ~ '3', year == 1997 ~ '4',
                                 year == 1998 ~ '5', year== 1999 ~ '6', 
                                 year == 2000 ~ '7', year== 2001 ~ '8',
                                 year== 2002 ~ '9', year == 2003 ~ '10',
                                 year== 2004 ~ '11', year == 2005 ~ '12',
                                 year == 2006 ~ '13', year == 2007 ~ '14',
                                 year == 2008 ~ '15', year == 2009 ~ '16',
                                 year == 2010 ~ '17',year == 2011 ~ '18',
                                 year == 2012 ~ '19',year == 2013~ '20',
                                 year == 2014 ~ '21',year == 2015 ~ '22',
                                 year == 2016 ~ '23',year == 2017 ~ '24',
                                 year == 2018~ '25',year == 2019 ~ '26')
  ) 
```


```{r, echo=FALSE}
# MODELLING MEAN DOY ----

# making study area categorical and year numeric
phenology_green_trim$study_area<- as.factor(as.character(phenology_green_trim$study_area))
phenology_green_trim$year_index<- as.numeric(phenology_green_trim$year_index)

# lmer with study_area as random effect 
lmer_green <- lmer(mean.doy ~ year_index + (1 |study_area) + (1|year_index), data = phenology_green_trim ) 
summary(lmer_green)

plot(lmer_green)

```

```{r, fig.show = "hide"}
# Extract predictions
pred_phen <- ggpredict(lmer_green, terms = c("year_index", "study_area"), type = "re") %>%
    rename(study_area = group)


# Plot the predictions 
(pheno_preds <- ggplot(pred_phen, aes(x = x, y = predicted, colour = study_area)) +
        stat_smooth(method = "lm", aes(colour = study_area, fill = study_area),size = 1.5) +
        facet_wrap(~study_area, ncol = 2))+
        geom_ribbon(aes(ymin = conf.low, ymax = conf.high, fill = study_area), alpha = 0.1) +
        geom_point(data = phenology_green_trim,                   
                   aes(x = year_index, y = mean.doy, colour = study_area), size = 2.5) +
    scale_colour_manual(values = c("#332288", "#117733", "#DDCC77", "#CC6677"))+
    scale_fill_manual(values = c("#332288", "#117733", "#DDCC77", "#CC6677"))+
    scale_x_continuous(breaks=c(2,6,10,14,18,22,26))+
    labs(x = "\nYear (indexed)", y = "Mean greening DOY (%)\n") +
    #theme_shrub()+
    theme(axis.text.x  = element_text(vjust=0.5, size=20, angle= 0, 
                                      colour = "black"), 
          legend.position = "none",
          axis.title.x = element_text(size=25),
          axis.title.y = element_text(size=25),
          strip.text.x = element_text(size = 25, face = "italic" ))

```

```{r}
# Separate models per study area ----

# Qikiqtaruk -----
Qikiqtaruk <-  phenology_green_trim %>% filter (study_area == "Qikiqtaruk") 

# Model
lmer_Qiki <- lmer(mean.doy ~ year_index + (1|year_index), data =Qikiqtaruk ) 
summary(lmer_Qiki)
plot(lmer_Qiki)

# Extracted and plotted model predictions
# also modeled other 3 study areas
```


